# Generated by Django 3.2 on 2021-10-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20211028_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, verbose_name='долгота'),
        ),
    ]
