# Generated by Django 3.2 on 2021-10-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой'), ('not_selected', 'Не выбран')], db_index=True, default='not_selected', max_length=13, verbose_name='оплата'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'Обработаный'), ('not_processed', 'Необработанный')], db_index=True, default='not_processed', max_length=13, verbose_name='статус'),
        ),
    ]
