# Generated by Django 3.2 on 2021-11-06 14:11

from django.db import migrations


def set_price_to_order_items(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for order_item in OrderItem.objects.filter(price__isnull=True).iterator():
        order_item.price = order_item.product.price
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20211106_1407'),
    ]

    operations = [
        migrations.RunPython(set_price_to_order_items),
    ]
