# Generated by Django 3.2 on 2021-10-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_rename_status_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='order_payment',
        ),
    ]
