# Generated by Django 3.2 on 2021-10-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20211028_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_1',
            field=models.CharField(choices=[('processed', 'Обработаный'), ('not_processed', 'Необработанный')], db_index=True, default='not_processed', max_length=13, verbose_name='статус'),
        ),
    ]
