# Generated by Django 3.2 on 2021-10-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_status_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status_1',
            new_name='processing_status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой'), ('not_selected', 'Не выбран')], db_index=True, default='not_selected', max_length=13, verbose_name='оплата'),
        ),
    ]
